### ISSUE TITLE
converting links has error

### ISSUE THREAD

**Issue by lichtkind** [softmoth/perl6-pod-to-markdown#16]
as you can see https://github.com/pierre-vigier/Perl6-Math-Matrix under Methods, the link to the gist method works but the label contains the # which should not be visible.

in plain text

L< # gist > is translated to  [ # gist] ( # gist) but it should be: [ gist ] ( # gist )

(added space to fool local converter)
Thanks

**Comment by lichtkind** [comment]
found you can write L<label | # link> too but maybe you want still accept the patch

**Comment by softmoth** [comment]
Thanks, Herbert. I think I would keep it as is, because it matches what the Perl5 Pod::Markdown module does already. AFAIK the behavior isn't specified in p6doc or in S26, so following Perl5 behavior makes sense to me. I welcome any feedback that would clarify this better.

**Comment by lichtkind** [comment]
fair enough, what I proposed would just add a little convenience in case you don't provide a link label, because then you usually don't want to see the # but alright , so I guess you could close the issue as rejected :)

**Comment by softmoth** [comment]
Either way, I appreciate the bug report. I'll close it, but keep this in mind.

**Comment by softmoth** [comment]
I think HTML converter probably has far more users, and I consider consistency there to be more relevant than consistency w/ Perl5's Pod::Markdown, so I'll re-open this. I think I want to tweak the patch to ensure only a `'#'` prefix is removed.
