### ISSUE TITLE
Raku pod Unicode syntax 'E<0xnnnn>' is not being translated to Github Markdown

### ISSUE THREAD

**Issue by tbrowder** [softmoth/perl6-pod-to-markdown#26]
These specific Raku pod hexadecimal Unicodes for *math symbols inside Raku tables* are not being translated into proper Github Markdown syntax **inside Github Markdown tables**:

Name | Raku pod syntax | Github Markdown syntax
--- | --- | ---
left floor              | E<0x230a> | \&\#x230a;
right floor            | E<0x230b> | \&\#230b;
math middle dot | E<0x22c5> | \&\#22c5;

I realize Raku pod formatting in table cells is not yet properly handled by Raku, but it would be useful to somehow preprocess the input pod table cells and convert the *E<>* blocks to Markdown.

**Comment by softmoth** [comment]
Thanks, Tom. Can you provide a (very short is fine) example of just what input you want to have work? I think I understand, but a brief Pod example would ensure clarity.

**Comment by tbrowder** [comment]
I will try to put the exact source below inside a fenced code block later today.

**Comment by tbrowder** [comment]
I just found a spurious ';' inside one of the E<> blocks which may have caused the problem. Checking it now...

**Comment by softmoth** [comment]
I'll look into adding this soon.

**Comment by tbrowder** [comment]
Thanks, Tim!
